# Generated by Django 5.2.4 on 2025-10-22 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_messages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="textmessage",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="videomessage",
            name="sender",
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                ("room_type", models.CharField(max_length=20)),
                ("room_id", models.BigIntegerField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("video", "视频"),
                            ("file", "文件"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="内容"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chat/files/",
                        verbose_name="文件",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="文件名"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="FileMessage",
        ),
        migrations.DeleteModel(
            name="ImageMessage",
        ),
        migrations.DeleteModel(
            name="TextMessage",
        ),
        migrations.DeleteModel(
            name="VideoMessage",
        ),
    ]
