# Generated by Django 5.2.4 on 2025-10-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_messages",
            "0002_remove_imagemessage_sender_remove_textmessage_sender_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message_type",
            new_name="type",
        ),
    ]
