# Generated by Django 5.2.4 on 2025-10-31 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChatRoom",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="群聊名称")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="group_avatars/",
                        verbose_name="群聊头像",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="群聊描述"),
                ),
                (
                    "admin",
                    models.ManyToManyField(
                        related_name="admin_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="群聊管理员",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="group_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="群聊成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "群聊房间",
                "verbose_name_plural": "群聊房间",
            },
        ),
        migrations.CreateModel(
            name="PrivateChatRoom",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_rooms_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_rooms_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "私聊房间",
                "verbose_name_plural": "私聊房间",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("user1", models.F("user2")), _negated=True),
                        name="no_self_private_chat",
                    )
                ],
                "unique_together": {("user1", "user2")},
            },
        ),
    ]
