# Generated by Django 5.2.4 on 2025-10-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_messages", "0003_rename_message_type_message_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="type",
        ),
        migrations.AddField(
            model_name="message",
            name="messages_type",
            field=models.CharField(
                choices=[
                    ("text", "文本"),
                    ("image", "图片"),
                    ("video", "视频"),
                    ("file", "文件"),
                ],
                default="text",
                max_length=10,
                verbose_name="消息类型",
            ),
        ),
    ]
